version: '3'
services:
    web:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"
        links:
            - php
    php:
        image: php:7-fpm
        volumes:
            - ./code:/var/www/html
        links:
            - db
    db:
        image: mariadb
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: database
        ports:
            - "3306:3306"